services:
  - type: web
    name: hcp-engagement-api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: GROQ_API_KEY
        sync: false  # This needs to be set manually in Render dashboard
      - key: REDIS_URL
        value: redis://localhost:6379/0  # Will be updated if Redis is added
    autoDeploy: true
